
apiVersion: v1
kind: Service
metadata:
  name: expose-daemon
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: daemon
  externalIPs:
    - {{ .Values.exposeIP }}
  ports:
    - name: ssh
      protocol: TCP
      port: {{ .Values.sshListenPort }}
      targetPort: {{ .Values.sshListenPort }}