apiVersion: v1
kind: ServiceAccount
metadata:
  name: daemon-account
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.namespace }}-daemon-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "pods/attach", "secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace}}-daemon-account-role-binding
subjects:
  - kind: ServiceAccount
    name: daemon-account
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.namespace}}-daemon-role
  apiGroup: rbac.authorization.k8s.io