---
apiVersion: v1
kind: Namespace
metadata:
  name: linode-cli
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: daemon-account
  namespace: linode-cli
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: linode-cli
  name: daemon-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "pods/attach"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: daemon-account-role-binding
  namespace: linode-cli
subjects:
  - kind: ServiceAccount
    namespace: linode-cli
    name: daemon-account
roleRef:
  kind: ClusterRole
  name: daemon-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemon-deployment
  namespace: linode-cli
  labels:
    app: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      serviceAccountName: daemon-account
      containers:
        - name: daemon
          image: lbgarber/cli-autodeploy-daemon:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 2222
---
apiVersion: v1
kind: Service
metadata:
  name: expose-daemon
  namespace: linode-cli
spec:
  selector:
    app: daemon
  externalIPs:
    - YOURIPHERE
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
